# Generated by Django 4.2.7 on 2025-12-07 23:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercampaign',
            name='content_html',
            field=tinymce.models.HTMLField(help_text='HTML content of the email'),
        ),
    ]
